# Generated by Django 5.2.6 on 2025-12-02 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("style_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("colorful", "Colorful"),
                            ("casual", "Casual"),
                            ("hand-drawn", "Hand-drawn"),
                            ("formal", "Formal"),
                            ("monochrome", "Monochrome"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Visual Style",
                "verbose_name_plural": "Visual Styles",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Visual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Main text content to visualize"),
                ),
                (
                    "context",
                    models.TextField(
                        blank=True,
                        help_text="Additional context for generation",
                        null=True,
                    ),
                ),
                (
                    "napkin_request_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("style_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "visual_query",
                    models.CharField(
                        blank=True,
                        help_text="E.g., mindmap, flowchart, timeline",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("svg", "SVG"), ("png", "PNG"), ("ppt", "PowerPoint")],
                        default="png",
                        max_length=10,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                ("file_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("transparent_background", models.BooleanField(default=False)),
                (
                    "color_mode",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("both", "Both"),
                        ],
                        default="light",
                        max_length=10,
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("horizontal", "Horizontal"),
                            ("vertical", "Vertical"),
                            ("square", "Square"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        blank=True, help_text="Width in pixels (PNG only)", null=True
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True, help_text="Height in pixels (PNG only)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visuals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Visual",
                "verbose_name_plural": "Visuals",
                "ordering": ["-created_at"],
            },
        ),
    ]
