# Generated by Django 5.0.14 on 2025-12-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visual",
            name="language",
            field=models.CharField(
                default="en",
                help_text="Language code (e.g., en, es, fr)",
                max_length=10,
            ),
        ),
    ]
