# Generated by Django 5.2.6 on 2025-10-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0003_alter_uploadedimage_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="task",
            field=models.CharField(
                choices=[
                    ("equation", "Equation"),
                    ("table", "Table"),
                    ("table_gemini", "Table(Gemini)"),
                    ("groq", "Groq"),
                ],
                max_length=20,
            ),
        ),
    ]
