# Generated by Django 5.2.6 on 2025-10-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0005_rename_table_groq_to_groq"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="model_used",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
