# Generated by Django 5.2.6 on 2025-10-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0006_uploadedimage_model_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="task",
            field=models.CharField(
                choices=[
                    ("equation", "Equation"),
                    ("table", "Table"),
                    ("table_gemini", "Table(Gemini)"),
                    ("groq", "Groq"),
                    ("grok2", "Grok 2"),
                ],
                max_length=20,
            ),
        ),
    ]
