# Generated by Django 5.2.6 on 2025-11-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0009_alter_uploadedimage_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="task",
            field=models.CharField(
                choices=[
                    ("equation", "Equation"),
                    ("table", "Table"),
                    ("table_gemini", "Gemini"),
                    ("groq", "Groq"),
                    ("grok2", "Grok 2"),
                    ("mistral", "Mistral"),
                    ("deepseek_diagram", "DeepSeek (Diagram)"),
                    ("openai_diagram", "OpenAI (Diagram)"),
                ],
                max_length=20,
            ),
        ),
    ]
