# Generated by Django 5.2.6 on 2025-11-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0011_alter_uploadedimage_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="task",
            field=models.CharField(
                choices=[
                    ("equation", "Equation (LaTeX OCR)"),
                    ("table", "Table (Tesseract)"),
                    ("table_gemini", "Table/Equation (Gemini AI)"),
                    ("groq", "Table/Equation (Groq AI)"),
                    ("grok2", "Table/Equation (Grok 2 AI)"),
                    ("mistral", "Table/Equation (Mistral AI)"),
                    (
                        "gemini_universal",
                        "Universal: Equation/Table/Diagram (Gemini AI - Auto-Detect)",
                    ),
                    ("deepseek_diagram", "Diagram Template (TikZ)"),
                    (
                        "deepseek_diagram_ai",
                        "Diagram AI-Powered (DeepSeek - Requires Credits)",
                    ),
                    (
                        "huggingface_diagram",
                        "Diagram Intelligent Template (HuggingFace Analysis)",
                    ),
                    ("openai_diagram", "Diagram AI-Powered (OpenAI GPT-4o)"),
                    ("gemini_diagram", "Diagram AI-Powered (Gemini 2.0 Flash)"),
                ],
                max_length=20,
            ),
        ),
    ]
