# Generated by Django 5.2.6 on 2025-12-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0012_alter_uploadedimage_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="task",
            field=models.CharField(
                choices=[
                    ("equation", "Equation (LaTeX OCR)"),
                    ("table", "Table (Tesseract)"),
                    ("table_gemini", "Table/Equation (Gemini AI)"),
                    ("groq", "Table/Equation (Groq AI)"),
                    ("mistral", "Table/Equation (Mistral AI)"),
                    (
                        "gemini_universal",
                        "Universal: Equation/Table/Diagram (Gemini AI - Auto-Detect)",
                    ),
                    ("gemini_diagram", "Diagram AI-Powered (Gemini 2.0 Flash)"),
                ],
                max_length=20,
            ),
        ),
    ]
