# Generated by Django 5.0.14 on 2025-12-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0013_alter_uploadedimage_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="feedback",
            field=models.TextField(
                blank=True, help_text="Validator feedback", null=True
            ),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="retry_count",
            field=models.IntegerField(
                default=0, help_text="Number of conversion retry attempts"
            ),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="scribble_type",
            field=models.CharField(
                blank=True,
                help_text="Classified type: equation/table/diagram",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="type_confidence",
            field=models.FloatField(
                blank=True, help_text="Classification confidence score 0-1", null=True
            ),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="validation_score",
            field=models.FloatField(
                blank=True, help_text="Validation quality score 0-1", null=True
            ),
        ),
        migrations.AlterField(
            model_name="uploadedimage",
            name="task",
            field=models.CharField(
                choices=[
                    (
                        "agent",
                        "Agent Workflow: Auto-Classify & Convert (Multi-Agent AI)",
                    ),
                    (
                        "gemini_universal",
                        "Universal: Equation/Table/Diagram (Gemini AI - Auto-Detect)",
                    ),
                    (
                        "mistral_universal",
                        "Universal: Equation/Table/Diagram (Mistral AI - Auto-Detect)",
                    ),
                    (
                        "groq_universal",
                        "Universal: Equation/Table/Diagram (Groq AI - Auto-Detect)",
                    ),
                    ("equation", "Equation (LaTeX OCR)"),
                    ("table", "Table (Tesseract)"),
                ],
                max_length=20,
            ),
        ),
    ]
