# Generated by Django 5.2.7 on 2025-11-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilerun',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='compiled_pdfs/'),
        ),
    ]
