# Generated by Django 5.2.7 on 2025-11-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_compilerun_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compilerun',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='compilerun',
            name='pdf_path',
        ),
        migrations.AlterField(
            model_name='compilerun',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='compile_pdfs/'),
        ),
    ]
