# Generated by Django 5.2.7 on 2025-11-04 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_alter_compilerun_options_remove_compilerun_pdf_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilerun',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='project_pdfs/'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_folders', to='editor.folder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='editor.project')),
            ],
            options={
                'unique_together': {('project', 'parent', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='editor.folder'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('project', 'folder', 'name')},
        ),
        migrations.CreateModel(
            name='BinaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binaries', to='editor.project')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='binaries', to='editor.folder')),
            ],
            options={
                'unique_together': {('project', 'folder', 'file')},
            },
        ),
    ]
