# Generated by Django 5.0.1 on 2025-12-02 05:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='compiler.folder')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LatexFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('tex', 'LaTeX Document'), ('bib', 'Bibliography'), ('cls', 'Class File'), ('sty', 'Style File'), ('txt', 'Text File')], default='tex', max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='compiler.folder')),
            ],
            options={
                'verbose_name': 'LaTeX File',
                'verbose_name_plural': 'LaTeX Files',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='compiler.latexfile')),
            ],
            options={
                'verbose_name': 'File Version',
                'verbose_name_plural': 'File Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latex_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LaTeX Project',
                'verbose_name_plural': 'LaTeX Projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='latexfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='compiler.project'),
        ),
        migrations.AddField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='compiler.project'),
        ),
        migrations.CreateModel(
            name='CompilationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('compiling', 'Compiling'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='compiled_pdfs/')),
                ('error_log', models.TextField(blank=True, null=True)),
                ('compiled_at', models.DateTimeField(auto_now_add=True)),
                ('compilation_time', models.FloatField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compilations', to='compiler.latexfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compilations', to='compiler.project')),
            ],
            options={
                'verbose_name': 'Compilation Result',
                'verbose_name_plural': 'Compilation Results',
                'ordering': ['-compiled_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='latexfile',
            unique_together={('project', 'folder', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('project', 'parent', 'name')},
        ),
    ]
