# Generated by Django 5.0.1 on 2025-12-02 05:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="conversions/%Y/%m/%d/")),
                ("latex_code", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Conversion History",
                "verbose_name_plural": "Conversion Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
