# Generated by Django 5.0.14 on 2025-12-02 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="conversions/%Y/%m/%d/"
                    ),
                ),
                ("latex_code", models.TextField()),
                (
                    "conversion_type",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("canvas", "Canvas"),
                            ("capture", "Capture"),
                        ],
                        default="upload",
                        max_length=20,
                    ),
                ),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Conversion Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
