# Generated by Django 5.0.14 on 2025-12-02 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversionhistory",
            name="converted_output",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="conversionhistory",
            name="input_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="conversions/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="conversionhistory",
            name="latex_output",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="conversionhistory",
            name="latex_code",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="conversionhistory",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="conversionhistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
