# Generated by Django 5.2.8 on 2025-12-02 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_conversionhistory_converted_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionhistory',
            name='detected_content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversionhistory',
            name='task_type',
            field=models.CharField(choices=[('equation', 'Equation'), ('table', 'Table'), ('diagram', 'Diagram'), ('auto', 'Auto-Detect')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='conversionhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conversionhistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
